development:
  sessions:
    default:
      database: lenvyx_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: lenvyx_test
      hosts:
        - localhost:27017
      <% if ENV['DB_PWD'] %>
      username: lenvyx
      password: <%= ENV['DB_PWD'] %>
      <% end %>
production:
  sessions:
    default:
      database: lenvyx
      hosts:
        - localhost:27017
      username: lenvyx
      password: <%= ENV['DB_PWD'] %>
